### ISSUE TITLE
gplus.to is no more

### ISSUE THREAD

**Issue by jwilk** [paultag/notes.pault.ag#5]
At the bottom of the page, there's a link to <http://gplus.to/paultag>.
But apparently this site has ceased to be:
```
$ wget http://gplus.to/paultag
--2016-07-19 16:57:55--  http://gplus.to/paultag
Resolving gplus.to (gplus.to)... failed: Name or service not known.
wget: unable to resolve host address ‘gplus.to’
```

**Comment by paultag** [comment]
Man, all my social buttons are gone - first rdio, next gplus, RIP little guys.
